export const questionTypeEnum = [
  'TEXT_BOX',
  'NUMBER_BOX',
  'TEXT_AREA',
  'SINGLE_DROPDOWN',
  'MULTI_DROPDOWN',
  'FILE_UPLOAD',
  'RADIO',
  'CHECKBOX',
  'DATE_PICKER',
  'DATERANGE_PICKER',
  'PIN_LOCATION',
  'POLYGON',
]
